apiVersion: zeabur/v1
kind: Template
metadata:
  name: S4N Donate System
  description: Open source streamer sponsorship platform with ECPay/O'Pay support and OBS alerts.
  coverImage: https://zeabur.com/deployed-on-zeabur-dark.svg
spec:
  services:
    - name: s4n-donate-system
      serviceName: s4n-donate-system
      repo:
        url: https://github.com/zeabur/s4n-donate-system # This will be replaced by user's repo
        branch: main
      build:
        command: npx prisma generate && npx prisma db push && npm run build
      env:
        - name: DATABASE_URL
          value: ${POSTGRES_URL}
        - name: ECPAY_MERCHANT_ID
          value: "2000132"
        - name: ECPAY_HASH_KEY
          value: "5294y06JbISpM5x9"
        - name: ECPAY_HASH_IV
          value: "v77hoKGq4kWxNNIS"
        - name: OPAY_MERCHANT_ID
          value: "2000132"
        - name: OPAY_HASH_KEY
          value: "5294y06JbISpM5x9"
        - name: OPAY_HASH_IV
          value: "v77hoKGq4kWxNNIS"
        - name: NEXT_PUBLIC_BASE_URL
          value: ${ZEABUR_WEB_URL}

    - name: postgres
      serviceName: postgres
      image: postgres:15-alpine
      ports:
        - port: 5432
          type: TCP
      env:
        - name: POSTGRES_PASSWORD
          value: ${PASSWORD}
